build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-pushover
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-pushover
    tag: develop
    when:
      branch: develop

plugin:
  name: Pushover
  desc: Send build status notifications via Pushover
  type: notify
  image: plugins/drone-pushover
  labels:
    - pushover
